# Generated by Django 4.2.6 on 2023-10-31 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_on', models.DateField(auto_created=True)),
                ('file_data', models.FileField(upload_to='')),
            ],
        ),
    ]
