# Generated by Django 4.2.6 on 2023-11-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_reduction', '0002_alter_excelfile_uploaded_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('columns', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField()),
            ],
        ),
    ]
