# Generated by Django 4.2.6 on 2023-11-12 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pomo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='check_off',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='position',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.CreateModel(
            name='TaskPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(null=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pomo.task')),
            ],
        ),
    ]
