# Generated by Django 4.2.6 on 2023-11-12 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pomo', '0002_alter_task_check_off_alter_task_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='position',
        ),
    ]
