# Generated by Django 4.2.6 on 2023-11-13 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pomo', '0003_remove_task_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='timer',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TaskSelected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pomo.task')),
            ],
        ),
    ]
