# Generated by Django 4.2.6 on 2024-01-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomo', '0003_tasktemplateitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplate',
            name='task',
            field=models.ManyToManyField(to='pomo.tasktemplateitem'),
        ),
    ]
