# Generated by Django 4.2.6 on 2023-11-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomo', '0004_timer_is_active_timer_is_paused_taskselected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timer',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
