# Generated by Django 4.2.6 on 2024-03-14 16:45

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('pomo', '0005_tasktemplate_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='timer',
            managers=[
                ('custom', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='timer',
            name='total_time',
            field=models.IntegerField(default=25),
        ),
    ]
