# Generated by Django 4.2.6 on 2023-11-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomo', '0005_alter_timer_end_time_alter_timer_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paused',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='timer',
            name='paused',
            field=models.ManyToManyField(to='pomo.paused'),
        ),
    ]
