# Generated by Django 4.2.6 on 2023-11-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomo', '0006_paused_timer_paused'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paused',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timer',
            name='paused',
            field=models.ManyToManyField(null=True, to='pomo.paused'),
        ),
    ]
