# Generated by Django 4.2.6 on 2023-11-15 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pomo', '0008_alter_timer_paused'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timer',
            old_name='is_active',
            new_name='is_completed',
        ),
    ]
