# Generated by Django 4.2.6 on 2023-11-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomo', '0009_rename_is_active_timer_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='completion_time',
            field=models.DateField(null=True),
        ),
    ]
