# Generated by Django 4.2.6 on 2023-11-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomo', '0010_timer_completion_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='completion_time',
            field=models.DateTimeField(null=True),
        ),
    ]
