# Generated by Django 4.2.6 on 2023-11-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomo', '0011_alter_timer_completion_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='delete_task',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
