# Generated by Django 4.2.6 on 2023-11-15 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pomo', '0012_task_delete_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='delete_task',
            new_name='is_deleted',
        ),
    ]
