# Generated by Django 4.2.6 on 2023-12-01 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pomo', '0014_remove_taskselected_selected_taskselected_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_break', models.CharField(max_length=10)),
                ('long_break', models.CharField(max_length=10)),
                ('pomodoro', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pomo_time', models.IntegerField()),
                ('short_break_time', models.IntegerField()),
                ('long_break_time', models.IntegerField()),
                ('theme', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='pomo.theme')),
            ],
        ),
    ]
