# Generated by Django 4.2.6 on 2023-12-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomo', '0015_theme_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
