# Generated by Django 4.2.6 on 2023-12-09 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pomo', '0020_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
