# Generated by Django 4.2.6 on 2023-12-09 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pomo', '0022_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='user',
        ),
    ]
