# Generated by Django 4.2.6 on 2024-03-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customization',
            name='category',
            field=models.CharField(default='Category', max_length=200),
        ),
        migrations.AlterField(
            model_name='customization',
            name='color',
            field=models.CharField(default='Color', max_length=10),
        ),
        migrations.AlterField(
            model_name='todo',
            name='custom_color_code',
            field=models.CharField(default='Color', max_length=10),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(default='Title', max_length=100),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='title',
            field=models.CharField(default='Title', max_length=200),
        ),
    ]
